lua/treesitter-context.lua

Errors are possible when trying to create a context window for another window that is too small.
By the way, thanks for creating this plugin; it's very nice! :)

Don't create a context window with width <= 0.

---

lua/treesitter-context.lua

Hi again! I thought I'd try and fix 2 other issues that I've seen:
- This PR fixes E11 errors when opening the command-line window while the context window is open (see https://github.com/neovim/neovim/pull/10738):
- This PR also improves the accuracy of `get_gutter_width()` by using Vim's `wincol()` function:
This improvement also seems to eliminate the need for my previous PR #2 for small windows.
Cheers!

Fix E11 and improve get_gutter_width() accuracy

---

lua/treesitter-context.lua

Hi again!
I've made some more small changes; details are in the commit messages.
The `WinLeave` split bug is a bit strange, though:
Might possibly be caused by an issue with `nvim_win_set_config()`?
WinEnter is triggered before the file is loaded, but after the window is split when splitting windows, which maybe causes that issue _somehow_, but the same thing does not happen if `nvim_win_open()` is used instead...

More improvements.

---

lua/treesitter-context.lua

This reverts commit e599c7e2515f3b6be7f3b16eb5e934f1905b5c09.
@seandewar I need to revert this commit due to the bug shown below. Modifying the cursor position mid-function clears the [curswant](https://github.com/neovim/neovim/blob/b5cd052037c532e5416919e4077b721ce6ab3a38/src/nvim/buffer_defs.h#L1140) property. If you have a different proposition to measure the gutter width let me know. Also I'm not sure which issue it solved but if you encounter it please open it so it's documented :)

Revert "Improve get_gutter_width() accuracy using wincol()"

---

lua/treesitter-context.lua

Fingers crossed that `get_gutter_width()` has no more surprises! 😆
Closes #16.

fix: get_gutter_width() horizontal scroll issues

---

lua/treesitter-context.lua

Since https://github.com/neovim/neovim/pull/13252 got merged, `nvim-treesitter-context` would error out sue to API incompatibilities.
This is just my quick attempt to get it back to work using the new `highlighter` API.

fix: use new TS Highlighter API

---

lua/treesitter-context.lua

`winrestview()` causes the whole screen to be redrawn which in turn causes treesitter to reset all the highlights. On it's own this isn't too bad but combined with the fact that `winresetview()` is triggered on CursorMoved (any other autocmds) leads to the screen being unnecessarily redrawn very often.
`nvim_win_set_cursor()` is much more lightweight and doesn't force the whole screen to be redrawn.

Don't call winrestview during cursorMoved 

---

README.md
lua/treesitter-context.lua

Fixes: #29
I don't know how to use the API to define highlight links. Thereby it is a plain command string for the moment. I'm glad if someone could help here.

Add highlight group for customization

---

lua/treesitter-context.lua

I usually work with multiple windows and multiple tabs, and I discovered that if you have a window with a context window open as the last window in a tab, and you try to close with `:q`, you get an `E5601`:
I added a close autocmd on `QuitPre` which prevents the error.

Close context window on QuitPre

---

lua/treesitter-context.lua

From [issue](https://github.com/romgrk/nvim-treesitter-context/issues/25). This pr allows `nvim-treesitter-context` to use the locals queries provided by `nvim-treesitter`. It also allows for multi line context. I can't get the highlighting to extract the colors from the saved buffer so for now i just call `ts_highlight.attach(bufnr, ft)`which has worse syntax highlighting. Any ideas about how to implement proper syntax highlighting other than calling `ts_highlight.attach`?

Use nvim-treesitter locals queries

---

lua/treesitter-context.lua

This fixes an issue i had trying to use nvim-treesitter-context while editing files with foldmarkers and a modeline. Everytime i moved my cursor all my folds were getting closed. I found out that `doautocmd` reloads the `modeline` which caused `foldlevel=0` from my modeline to be run again. Fortunately this can be suppressed using the `<nomodeline>` flag. I replaced every `doautocmd` call with `doautocmd <nomodeline>`.
Use the following file and command to reproduce: `nvim --clean -u test.vim test.vim`
```vim
" Test {{{
set modeline
au User Test echom 'test'
" }}}
" vim: foldmethod=marker foldenable foldlevel=0
```

Fix problem with doautocmd and modeline

---

lua/treesitter-context.lua

As mentioned in the referenced PR, the issue was that showing the context window was interfering with barbar displaying the current buffer as active. Previously, ts-context was calling `show()` (and thus `nvim_open_win`) from inside an autocmd handler (frequently `WinScrolled`). Because those autocmds were not declared as `++nested`, it prevented the `nvim_open_win` call from triggering any autocmds. With the introduction of throttling, the `show()` function is now getting called from inside a `defer_fn`, outside of any autocmd context. The fix is pretty simple and restores the previous behavior.

Fix the barbar focus issue introduced in #54

---

lua/treesitter-context.lua

Note that the upper node gets matched against values from `config.patterns.default` using `get_type_pattern()` which returns a regexp (i.e. the original value, say `function` gets returned as `%f[%w]function%f[^%w]`  having been wrapped with `word_pattern()`): this means that key `['function']` in `last_types` must be wrapped this same way (as `[word_pattern('function')]`) because its finally gets retrieved with `last_types[type]`.
Note also that `function_declaration` may be deeply nested inside `function_definition` (at least, in C), and therefore a correct implementation requires a recursive traversal of nodes which is implemented with function `find_node()` introduced in this commit.
Closes #65

Fixed multiline nodes (see #65)

---

README.md
lua/treesitter-context.lua

I was trying to make this neat piece of software work with my own TreeSitter grammar when I discovered
that matched node types are mapped with `word_pattern` function. In my grammar, I have `dict` and `dict_body` nodes and
I would like to match only `dict`.
So, I added a user setting to turn off that mapping, and use bare Lua patterns instead. Now I can live with `^dict$`.

Enable full lua patterns as node types on user demand

---

lua/treesitter-context.lua

Bug: The context line shows PHP 8 class or method attributes instead of the class/method definition. This PR is an attempt to fix that.
Before:
With this PR:
:TSPlayground
Test code:
```php
<?php
use Attribute;
#[Attribute(Attribute::TARGET_CLASS)]
class ClassAttr { }
#[Attribute(Attribute::TARGET_METHOD)]
class MethodAttr { }
/**
* hello
*/
#[ClassAttr]
class Inventory
{
/**
* @throws \Exception
*/
#[MethodAttr]
public static function testasdf(array $args): void
{
// asdf
}
}
```

Omit PHP attributes from class/method context.

---

lua/treesitter-context.lua

It is no longer necessary to rely on an Nvim internal C function.

Use getwininfo() instead of FFI to get gutter width in Nvim 0.6

---

lua/treesitter-context.lua

Improves compatibility with other plugins such as session managers that like to delete buffers. Previously, if another plugin deleted this plugin's buffer, treesitter-context would error out upon trying to show the context window. Now, the buffer is re-created if it doesn't exist. The buffer is also now deleted when `disable()` is called.
Side note:
<details>
<summary>Click to expand</summary>
This isn't directly related, but I don't really like having so many module-level state variables. I think the code would be nicer if they were all kept inside a `state` table:
```lua
-- Current
local didSetup = false
local enabled = nil
local winid = nil
local bufnr = api.nvim_create_buf(false, true)
local _bufnr = nil -- Don't access directly, use get_buf()
local ns = …
```

Ensure treesitter-context buffer exists

---

lua/treesitter-context.lua

Thank you for this awesome plugin! Especially since I discovered that I can easily extend the treesitter patterns to be added to the context :) 
This adds config to show function arguments for python and rust.

show function arguments for python and rust

---

lua/treesitter-context.lua

When creating a single context from multiple lines, if the amount of
lines reaches a specified threshold, then just use the first line.
The motivating use case is when passing in a large table to a function
in Lua, e.g. `packer.setup`.
Fixes #116

feat: add config.multiline_threshold

---

README.md
lua/treesitter-context.lua

Choices:
- 'cursor' (default): current behaviour, context is determined by
cursor position
- 'topline': context is determined by the top of the window
Resolves #77

feat: add config.mode

---

lua/treesitter-context.lua

This shows trailing return types in rust, python, and typescript by querying named fields of the function nodes. I don't know if this is the preferred way to implement this or if one would use queries (I have never touched that), but it seems to work quite well.

feat: show trailing return types

---

lua/treesitter-context.lua

there are nodes like `object_definition` in the scala treesitter, because you can do things like
```scala
object Foo {
def dank(): Unit = println("foodank")
}
Foo.dank()
```
where in other languages, like java, you would do
```java
class Foo {
public static void dank() { System.out.println("foodank"); }
}
Foo.dank();

add object to scala

---

Makefile
lua/treesitter-context.lua
test/nested_file.rs
test/ts_context_spec.lua

This fixes an issue in `topline` mode where sometimes context nodes don't get shown if they are covered by the popup. Essentially the `lnum` is incremented each time the window is known to be higher and the logic to collect parents is rerun.
This is probably the bug @rockyzhang24 mentioned in #128, which I failed to understand.
Before:
[![asciicast](https://asciinema.org/a/hCLS1zqEeqQL73MAv6ciMwHgx.svg)](https://asciinema.org/a/hCLS1zqEeqQL73MAv6ciMwHgx)
After:
[![asciicast](https://asciinema.org/a/Am906dIRB3UAloZCEypeX7XAm.svg)](https://asciinema.org/a/Am906dIRB3UAloZCEypeX7XAm)
The for loops and the `if let Some(stco) ...` line aren't shown as soon as they are covered by the popup before.

fix: covered context not showing in topline mode

---

lua/treesitter-context.lua

Self-explanatory. I feel like these two can be considered as sane default options.

Add struct and enum patterns to rust defaults

---

lua/treesitter-context.lua

Closes #136 
Seems like we already have the `line_numbers` code, but a few lines were missing. Also included fixes for an spurious error message on nvim exit.

fix: restore line_numbers & more

---

lua/treesitter-context.lua

This adds a pattern to show the current section in the markdown file. It works with headings and subheadings also. This uses the new markdown parser that was recently added to nvim-treesitter.

feat: add markdown pattern

---

lua/treesitter-context.lua

Closes #138 
Explicitly set the `nowrap` option on the context window.

fix: set option nowrap on context window

---

README.md

only discovered the `separator` configuration because i searched this repo for "border" and found issues about it (#55 + #119), so i figured a README update was in order.

add config.separator to README default config

---

README.md
lua/treesitter-context.lua

Elixir has patterns that aren't picked up with the current default config. Adding the list defined in https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/elixir/folds.scm works pretty well with codebases I've been using it with.
Nothing happens. No treesitter context output shown.
https://user-images.githubusercontent.com/27223/188254512-f65a43ff-3743-4a79-a858-75a2ac2fbc4e.mov
treesitter context works as expected with elixir source code
https://user-images.githubusercontent.com/27223/188254520-924f3cd8-9cd5-4d9f-ad42-d9ab890ea74a.mov

add elixir default type patterns

---

README.md
lua/treesitter-context.lua

Fixes [#122](https://github.com/nvim-treesitter/nvim-treesitter-context/issues/122)

fix: don't let separator cover the line when cursor at top

---

README.md
lua/treesitter-context.lua

This PR makes it possible to display keys of YAML and JSON.
| yaml | json |
|-|-|
| ![Screenshot_20220904_163706](https://user-images.githubusercontent.com/10358398/188303404-1f2af376-a6dc-4076-ba0b-b1b67d56bcf4.jpg) | ![Screenshot_20220904_164001](https://user-images.githubusercontent.com/10358398/188303407-7bcc257d-863f-45a1-a72b-c32316897c19.jpg) |

Support YAML and JSON by defaults

---

lua/treesitter-context.lua

I think `interface`, in addition to `class` makes sense for default groups that apply to many programming languages

🔧 [default]: Add `interface` to default patterns

---

lua/treesitter-context.lua

The haskell syntax tree has `adt` at the top of `data Blah where` declarations.
Sample of this working:

Show haskell types as context

---

README.md
lua/treesitter-context.lua

This is helpful if you have an editor with a bunch of tiny windows to not have them eaten up by context that there's not space for.

Only open on windows that are taller than some minimum window height

---

lua/treesitter-context.lua

Addresses #146
Sets `tabstop` same as the current buffer.

fix: inherit tabstop on context window

---

lua/treesitter-context.lua

Terraform uses `block`s for all their top level data structures. Ideally I'd add a query for those that have an identifier that starts with `resource`, `data`, `locals` or `provider`. But that doesn't seem possible within this plugin.

Add terraform default type patterns

---

lua/treesitter-context.lua

The existing throttling logic has a very significant downside: it adds a 50ms delay before updating the context floats. For some reason that little artifact bugged me enough to want to replace it, so here's my solution:
- On first call, run the recalculation with no delay.
- If the recalculation takes _more than 5ms_, put a lock in place for twice as long as the recalculation function blocked the main thread.
- If called again while locked, mark it as dirty (needing recalculation), and pass
- After the lock is released, run the recalculation if the dirty bit is set
This has the advantage of responding in realtime for most situations (smallish files), and dynamically adapting the throttling when the need arises (on larger files).
For comparison, I ran this test with the new throttle logic …

feat: dynamically throttle context calculation

---

README.md
lua/treesitter-context.lua

Adds a highlight to the bottom line of the context.
By default it does nothing, but I've been doing `hi TreesitterContextBottom gui=underline guisp=Grey`
to add a grey underline to the bottom to look like a border.
It's not perfect (see how it overlaps with the `f` and `p`; I guess it depends on your font),
but it does make a nice-ish border and saves a line compared to using the `separator` option.

Highlight the bottom line of context e.g. to add a border

---

lua/treesitter-context.lua

I've been having issues when I try to exit vim. It doesn't let me `:qall` because I have hidden, modified buffers. I think we should always set nomodified on these buffers to prevent that issue.

fix: set nomodified on context buffers

---

lua/treesitter-context.lua

I think `enum` and `struct`, in addition to `class` makes sense for default groups that apply to many programming languages

🔧 [default]: Add `enum` and `struct`  to default patterns

---

lua/treesitter-context.lua

When I'm trying to open a php file which contains an `#[Attribute]` before either `class_declaration` or `method_declaration` I getting following error:
```
Error detected while processing BufEnter Autocommands for "*":
Error executing lua callback: ...ugged/nvim-treesitter-context/lua/treesitter-context.lua:590: attempt to perform arithmetic on a nil value
stack traceback:
...ugged/nvim-treesitter-context/lua/treesitter-context.lua:590: in function 'highlight_contexts'
...ugged/nvim-treesitter-context/lua/treesitter-context.lua:694: in function 'open'
...ugged/nvim-treesitter-context/lua/treesitter-context.lua:738: in function 'fn'
...ugged/nvim-treesitter-context/lua/treesitter-context.lua:481: in function <...ugged/nvim-treesitter-context/lua/treesitter-context.lua:476>
```
Here is the …

fix: skip leading types before highlighting contexts

---

README.md
lua/treesitter-context.lua

This is probably a commonly added config by Typescript users - this PR adds support for export statements.

[default] Add Typescript export statements

---

README.md

Sync pattern defaults in readme.
Might be worth directly linking to the source in the readme to prevent duplication:
https://github.com/nvim-treesitter/nvim-treesitter-context/blob/c61464bafb13595a5927f60606f0440bd3d83336/lua/treesitter-context.lua#L86-L146

Update readme pattern defaults

---

lua/treesitter-context.lua

use `close()` function to close window instead of `M.close()`.

fix: close window in right way (#191)

---

lua/treesitter-context.lua

Example:
```python
def example_func():
file_name = "tmp/secrets.txt"
with open(file_name, "rb+") as f:
```
Will show both the function definition and the `with` line as context.

feat: support python's `with` statement

---

lua/treesitter-context.lua

Got bored and took a shot at #202 
This implementation has a few drawbacks: 
- Does not update until you scroll 
- Does not show all virtual text, only the stuff with namespaces
- Sometimes the ordering of the diagnostics and virtual text that shows at the end of a line flips
- Virtual text should always render right at the end of the line, diagnostics render to the right of it. 
But neotest virtual text, and lsp diagnostics do show up now
Still not showing the sign column information, I don't plan on adding that

Show virtual text in context bar

---

.github/workflows/ci.yml
Makefile
README.md
lua/treesitter-context.lua
queries/bash/context.scm
queries/c/context.scm
queries/cpp/context.scm
queries/json/context.scm
queries/lua/context.scm
queries/markdown/context.scm
queries/php/context.scm
queries/python/context.scm
queries/rust/context.scm
queries/scala/context.scm
queries/teal/context.scm
queries/toml/context.scm
queries/typescript/context.scm
queries/vim/context.scm
queries/yaml/context.scm
test/test.c
test/test.php
test/test.rs
test/test.ts
test/ts_context_spec.lua

This plugin has been significantly rewritten to use Treesitter queries instead of patterns for determining context regions for languages.
The main benefits of this change are:
- it is a much simpler implementation since we can leverage core APIs.
- it fits in more generally with the Treesitter eco-system.
- it allows configuration of contexts to be provided from multiples sources.
- it allows more sophisticated configuration of contexts since queries (with directives and predicates) are much more powerful than patterns.
- the query format should be usable for other editors.
The major downside of this new implementation is that it requires each language to provide it's own query as opposed to using the general purpose patterns. This means that some languages which had contexts before may …

feat!: use queries for determining context

---

queries/java/context.scm
test/test.java

Small PR to add Java queries.
The plugin seems to work in the actual editor, but when I tried to write test cases I couldn't get it to work for some reason. Inspecting it with the `screen:snapshot_util()` function would show up everything except the class declaration. Not sure what was going on there. Happy to include a test case if someone can advise.

add java queries

---

queries/python/context.scm

having `expression_statement` here leads to the first line of the docstring being part of the context, see 
which is not what I intended. 
I'll try some better definition, probably adding multi-line calls & assignments separately, but I would like to do this in a separate PR, after I tested some alternatives.

remove `expression_statement` from python context

---

queries/cpp/context.scm

Add context for linkage specification inside C++ code. For example, in
```c++
extern "C"
{
// SOME CODE
}
```
the line `extern "C" {` would sticky at the top for a sufficiently large amount of code in the block.

feat(cpp): add linkage specification context

---

Makefile
queries/cpp/context.scm
test/test.cpp
test/ts_context_spec.lua

The main reason for the pull request is to add a query for the C++ range based for loop. While I was at it I also decided to add a test file for the C++ language. I have included the test cases that are specified for the C language. I did this because they are separate languages and I think we should check that the features work in both, not just check C and assume that they work for C++. That being said, this introduces duplication of test code, if a test is added the the C file, the C++ test file needs to be updated as well.

Add cpp for range loop

---

queries/zig/context.scm
test/test.zig

I could not find any example for LoopType- and IfTypeExpr, and i do not understand enough about treesitter to write them using the tree-sitter-zig code.
The TypeExpr would essentially just be
```
(LoopTypeExpr
(_ (_TypeExpr (_) @context.end))
) @context
```
but i am not really sure if doing something like
```
(LoopTypeExpr
(_ (_ (_) @context.end))
) @context
```
is a good idea.
LoopStatement (https://github.com/maxxnino/tree-sitter-zig/blob/0d08703e4c3f426ec61695d7617415fff97029bd/grammar.js#L266):
```javascript
LoopStatement: ($) =>
seq(
optional(keyword("inline", $)),
choice($.ForStatement, $.WhileStatement)
),
ForStatement: ($) =>
choice(
seq($.ForPrefix, $.BlockExpr, optional($._ElseStatementTail)),
seq($.ForPrefix, $.AssignExpr, choice(SEMICOLON, $._ElseStatementTail))
), …
```

feat(zig): multiline

---

README.md
queries/graphql/context.scm
test/test.graphql

not really sure if this is needed, but if 'foo' in 
```graphql
foo {
foo1,
foo2,
foo3,
...
}
```
should also be highlighted 
```(arguments)``` would have to be removed from ```(selection( field```

feat(graphql): graphql support

---

queries/r/context.scm
test/test.r

This adds queries for (super_assignment) and (function_definition), makes existing queries show only relevent information, and drops the (right_assignment) query as it does not make sense to show the entire value.

Update R queries

---

README.md
lua/treesitter-context.lua

https://github.com/nvim-treesitter/nvim-treesitter-context/issues/190

feat: add context jump function

---

README.md
queries/usd/context.scm
test/test.usd

Now that the USD scene description language [is supported in nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter/pull/4774), I'd like to add it here to nvim-treesitter-context, too.
https://github.com/nvim-treesitter/nvim-treesitter-context/assets/10103049/e1d0be80-ab0c-40ee-86fb-3640724053c6
https://github.com/nvim-treesitter/nvim-treesitter-context/assets/10103049/c7c0afc0-a740-46e7-a649-05406f0c21f2
I've been using my own context.scm for a while and it works pretty well. In nested files it's so helpful! Please let me know if you'd like any changes.

Add USD language

---

queries/go/context.scm
test/test.go

This adds support for Go function literals. These are particularly useful when using testing frameworks like [Ginkgo](https://onsi.github.io/ginkgo).

feat(go): support func literals

---

README.md
lua/treesitter-context.lua

This allows customization of the separator's color without having to change the more general `FloatBorder` group.

feat: add TreesitterContextSeparator highlight group

---

README.md
queries/haskell/context.scm
test/test.hs

Tested locally and it works great. Not sure if there should be more nodes that the `context` should capture but they can be added in the future in the PR.
The image shows that how it look when running in the Haskell test file:

Add support for haskell

---

queries/diff/context.scm

Related: https://github.com/the-mikedavis/tree-sitter-diff/issues/8
This is how it looks like:
Closes #302

Add support for diff parser

---

queries/make/context.scm

Tested on https://salsa.debian.org/debian/curl/-/blob/57ba49f28ce6ea042a0457bc5741d9c40d9d5211/debian/rules
rule and conditional:
variable_assignment:
recipe_line:

Add support for make parser

---

lua/treesitter-context.lua

This is not a good fix but it does work.
I don't have a public reproduction, but the general behavior is scrolling causes this error. This PR just silences all errors from the offending call.
```
Error executing vim.schedule lua callback: ...ugged/nvim-treesitter-context/lua/treesitter-context.lua:409: Vim:Error executing lua callback: BufEnter Autocomma
nds for "*": Vim(append):Error executing lua callback: ...ugged/nvim-treesitter-context/lua/treesitter-context.lua:409: E565: Not allowed to change text or change window                                                                                                                                                       
stack traceback: …
```

Fix scrolling error: `treesitter-context.lua:409: E565: Not allowed to change text or change window`

---

README.md
lua/treesitter-context.lua
lua/treesitter-context/cache.lua
test/ts_context_spec.lua

Instead of collapsing all the lines in a node, instead display the node
on multiple lines if it requires it.
This should significantly simplify the highlighting logic since we don't
need to keep track of how lines are joined.

feat: better multiline contexts

---

lua/treesitter-context.lua

Issue:
- Currently there's a bug that the Treesitter Context is rendering in cmd  line window as well as still rendering (after closing cmd line window)
Fix:
- Do not render TS Context if it's a a cmd line window
After fix:

fix: TS Context Render on CMD Line Window

---

README.md
queries/julia/context.scm
test/test.jl

This PR adds support for the [Julia language](https://julialang.org). The `context.scm` file is mostly trial and error, so I'm happy to get suggestions if there are problems inside it.
I tried to get the following queries but did not manage to capture it:
- elseif_clause
- else_clause
- catch_clause
Is that because clauses are inside the parent statement respectively?

feat: Julia support

---

README.md

The `vim.treesitter.get_range()` function is used [here][1], but that function was only added in Neovim [0.9.0][2], in [this PR][3].
It was causing errors about a nil value being called whenever treesitter-context refreshed.
[1]: https://github.com/nvim-treesitter/nvim-treesitter-context/blob/9afe41b/lua/treesitter-context/render.lua#L143
[2]: https://github.com/neovim/neovim/releases/tag/v0.9.0
[3]: https://github.com/neovim/neovim/pull/22613

Bump required Neovim version to 0.9.0

---

queries/zig/context.scm

This fixes showing way too much context for structs (and possibly unions and friends).
BEFORE: 
AFTER:
Disclaimer: I have no experience with treesitter queries whatsoever. I just experimented and it happed to work out.

zig: Add missing @context.end to ErrorUnionExpr.

---

queries/javascript/context.scm

Add switch/case for javascript.
I have not figured out how to catch multiple cases that work on the same block yet, but this is better than nothing.
Multiple case that needs different query.
```
case A:
case B: {
}
```

javascript: add switch/case to the context.

---

README.md
queries/objdump/context.scm
test/test.objdump

Now that https://github.com/neovim/neovim/pull/23608 and https://github.com/nvim-treesitter/nvim-treesitter/commit/0179a89656b4ce395a4487c07ae385b8425524ae merged, objdump files are recognized in Neovim with tree-sitter support. Adding to nvim-treesitter-context as well.

Added objdump context and test

---

lua/treesitter-context.lua

This allows configurations to do things such as my use case of
notifying the new state when using .toggle()

feat: Add .is_enabled to check current status

---

.gitattributes

The language stats are skewed because the Janet test is somehow larger than the entire Lua codebase.

chore: ignore test languages

---

.github/workflows/ci.yml
Makefile
queries/c/context.scm
test/test.c
test/ts_context_spec.lua

A lot of the current C queries include an extra line with only `{` if you format your code in this style:
```c
if ()
{
//code
}
for ()
{
//code
}
```
For the context that whole line with only `{` is wasted space, so this simplifies some queries to not include that `{`. If you want to always include `{` instead, I can update the queries.
Also, this catches `if`, `else if` and `else` with the expected pattern (see #356). 
If the queries should catch the extra "{", then I can rewrite this a bit so it still catches `else if` and `else`, but otherwise doesn't change anything. 
Note: I can rewrite the test that is currently failing if you want to merge this pull request.

Update c queries and test

---

README.md
lua/treesitter-context.lua
lua/treesitter-context/render.lua

This closes #383.
For now I replaced `highlight_bottom` with `highlight_lno_bottom`, which will change the current behavior a bit, but also allow for more precise configuration by the user.
If you prefer to keep `highlight_bottom` as it was, I can add it back in together with the new function.

feat(hl): add 'TreesitterContextLineNumberBottom'

---

.github/workflows/ci.yml
.gitignore
.luarc.json
Makefile
lua/treesitter-context/render.lua
test/ts_context_spec.lua

fix: do not use vim.treesitter.highlighter

---

lua/treesitter-context/context.lua
test/test.html
test/test.md
test/ts_context_spec.lua

Currently, the plugin only recognizes the outermost language of a file, disregarding any injected languages within the file. A notable example are `.html` files, where JavaScript content within `<script>` tags is ignored.
The root cause of this behavior lies in the fact that, during context evaluation for a line, only the root language tree is considered. Fortunately, the `nvim-treesitter` API provides a solution by allowing us to retrieve all language trees associated with a given range (`LanguageTree:language_for_range({range})`).
This PR proposes a simple yet effective change: iterating over parent nodes of each language tree detected for the range, as opposed to doing so only for the root language tree.
I believe, introduced functionality aims to enhance the plugin's behavior without …

feat: Support context recognition for injected languages

---

lua/treesitter-context/render.lua

fix: set "fillchar" for 'statuscolumn' rendering

---

lua/treesitter-context/context.lua

Fixes #397
In #388 we have slightly refactored logic for acquiring langtree nodes for a line, and we did not recreate error handling logic existing previously. Thus, in case if the tree node for the given line cannot be found (e.g. due to the invalid syntax), the plugin crashes. Restoring the null handling seems to resolve the entire problem.

fix: crashes on lines with invalid syntax

---

lua/treesitter-context/render.lua

This reverts commit 4f5c7426978043b8eb76cf1cde44f399cf09ea0b, following the reports in #410.

Perf: revert "fix: do not use vim.treesitter.highlighter"

---

README.md
queries/gdscript/context.scm
test/test.gd

Created the context file, a test example and updated the readme to support gdscript (the Godot engine scripting language).

add gdscript support

---

queries/cpp/context.scm

Sometimes in complex c++ headers with several namespaces it's a bit hard to orient in which namespace you are currently working. Typically, there is one "public" namespace, and one "internal", and the file looks like this:
```c++
namespace public {
// some code
namespace internal {
// some code
}
// some code
}
```
The proposal is to add the namespace definition as the context line.

feat: add context for c++ namespace definition

---

lua/treesitter-context/render.lua

Seems to Fix #387
https://github.com/nvim-treesitter/nvim-treesitter-context/assets/130783534/fa4add42-52c1-48b1-8986-2eb961ae2dd6
Stable works fine without this.

fix(nighly): use get_hl_from_capture for nightly, instead of hl_cache

---

lua/treesitter-context/render.lua

Fix #431.
Scrolling down in a file when the first line is empty causes an error.
```
Error detected while processing WinScrolled Autocommands for "*":
Error executing lua callback: ...vim-treesitter-context/lua/treesitter-context/render.lua:51: 'height' key must be a positive Integer
stack traceback:
[C]: in function 'nvim_open_win'
...vim-treesitter-context/lua/treesitter-context/render.lua:51: in function 'display_window'
...vim-treesitter-context/lua/treesitter-context/render.lua:354: in function 'open'
.../lazy/nvim-treesitter-context/lua/treesitter-context.lua:50: in function 'open'
.../lazy/nvim-treesitter-context/lua/treesitter-context.lua:111: in function 'f'
.../lazy/nvim-treesitter-context/lua/treesitter-context.lua:27: in function …
```

fix: height error while scrolling down

---

README.md
queries/elm/context.scm
test/test.elm

Support elm https://elm-lang.org/
Adding type annotations support for functions would be great, but I don't have the required parser skills for now.

feat: add elm support

---

queries/ruby/context.scm

This PR contains two fixes for the Ruby/RSpec `.scm`.
Firstly, capturing as context `singleton_class` nodes:
```ruby
class Foo
class << self # this should count as context
def run
end
end
end
```
Secondly, correcting an RSpec type - `describe` blocks are used, not `description`:
```ruby
describe 'foo' do
context 'bar' do
end
end
```

Fixes for Ruby language support

---

queries/swift/context.scm

Add lambda_literal, which also defines a context in Swift and is used extensively in the language in the form of trailing closures.

fix(swift): add lambda_literal

---

queries/tact/context.scm

Minor renaming as node names changed in https://github.com/tact-lang/tree-sitter-tact

feat(tact): update queries

---

queries/cpp/context.scm

This PR adds context display for long bodies of lambda expressions. Works for me.
Regarding https://github.com/nvim-treesitter/nvim-treesitter-context/issues/466

add lambda_expression context for cpp

---

queries/ruby/context.scm

Resolves https://github.com/nvim-treesitter/nvim-treesitter-context/issues/469 where some context queries are not taken into account.
Add the following ruby context patterns:
1. `case`
2. `for`
3. `while`
4. `until`
5. `begin`
6. `rescue`
7.  `ensure`
8. `lambda`
Here is how the example from https://github.com/nvim-treesitter/nvim-treesitter-context/issues/469 is handled now:

Add missing ruby context patterns 

---

README.md
queries/devicetree/context.scm
test/lang/test.dts

This adds support for devicetree source (dts) files.

feat(devicetree): add devicetree support

---

lua/treesitter-context/context.lua

After https://github.com/neovim/neovim/commit/6913c5e1d975a11262d08b3339d50b579e6b6bb8 it is necessary to opt-in explicitly to the old behavior.

fix(query): use explicitly the legacy behavior

---

queries/java/context.scm

Allows to see which switch and which case you are in:

Add treesitter queries for switch and switch label

---

lua/treesitter-context.lua
lua/treesitter-context/context.lua

1. Fix the bug "Index out of bounds" https://github.com/nvim-treesitter/nvim-treesitter-context/issues/496 .
2. Support obtaining context & ranges from specified `bufnr`.

feat: multiwindow support; context

---

lua/treesitter-context.lua
lua/treesitter-context/render.lua

https://github.com/nvim-treesitter/nvim-treesitter-context/issues/507

fix: multiwindow support; fix bugs

---

lua/treesitter-context/render.lua

`vim.highlight` was renamed to `vim.hl` in https://github.com/neovim/neovim/pull/30840. This PR uses the new non-deprecated module when available.

fix: use vim.hl if available

---

lua/treesitter-context.lua

Fix #520 
1. made sure minimal testcase in #283 still works (see 2182556aab4524b4fa8d00031bf1228ea2e4a023)
2. made sure `on_attach()` return `false` does not display context (see minimal testcase in #520 )
3. made sure `on_attach()` return `true` display context (see minimal testcase in #520 )

fix: on_attach() return false to disable attaching

---

lua/treesitter-context.lua

Fixes https://github.com/nvim-treesitter/nvim-treesitter-context/issues/524 and https://github.com/nvim-treesitter/nvim-treesitter-context/issues/522
It is now possible to toggle multiwindow option at runtime.

fix: plugin reloading

---

queries/proto/context.scm
test/lang/test.proto

Have some long service definitions in my company and noticed the context didn't work for these.
This PR adds support for a context to the long service definition.

feat(proto): add contexts for service blocks

---

queries/javascript/context.scm
queries/tsx/context.scm
queries/typescript/context.scm

Queries for matching `for of` `for in` and `switch` expressions in `javascript`, `typescript` and `tsx`
Note that both `for in` and `for of` are matched by `for_in_statement` query
Closes #529

feat(js/ts/tsx): for in, for of, and switch context

---

lua/treesitter-context.lua

Should fix https://github.com/nvim-treesitter/nvim-treesitter-context/issues/522 reliably.
It is inspired by the satellite.nvim plugin https://github.com/lewis6991/satellite.nvim/blob/main/lua/satellite.lua#L74,  which is more stable and consistently uses deferred execution. In contrast, the current implementation sometimes uses deferred execution and other times executes callbacks in-place, when they are not throttled.
Also, there was a problem with throttler, the following execution was possible:
```
Time ->
|cb|-----timeout-------|cb||cb|-----timeout-----|cb||cb| ...
```

fix: defer execution to avoid segfaults and fix throttler

---

lua/treesitter-context/render.lua

Closes https://github.com/nvim-treesitter/nvim-treesitter-context/issues/533

feat: save unused buffers in buffer pool

---

lua/treesitter-context/render.lua
test/ts_context_spec.lua

When highlighting, if we find a capture that extends beyond the context,
instead of skipping it, clip the captured range to the bounds of the
context.

fix: highlighting for multi-line captures

---

queries/lua/context.scm

fix(lua): Filter comment-only lines from context view

---

queries/proto/context.scm
test/lang/test.proto

Was dealing with a large oneof and was missing the context for it. This adds the oneof as a context. Additionally, we also clean up the test proto a bit to be spaces instead of tabs, and also fix the syntax errors for the enum.

feat(proto): add context for oneof

---

README.md
queries/starlark/context.scm
test/lang/test.bzl

includes captures for if statements, function definitions, target or
macro calls, dicts and lists. special care was taken to not include
comments inside the context block while still allowing for multiline
function and if context blocks.
relies on #565 for tests to run

feat(starlark): add support

---

.luarc.json
README.md
test/contexts_spec.lua

previously, we only ran tests for when the treesitter language name is
the same as the extension name, but this is not the case for many
languages. in this commit, we add support for these excluded tests. For
example, test.sol was excluded because the test searches for
test.solidity which does not exist. Now, we get all files in test/lang/*
and group them by filetype, get the filetype for each treesitter
language, and run the tests that match the filetype.
The largest motivator for this is adding starlark support, which has
files with the extension .bzl.

test: support tests with different extensions than the lang name

---

README.md
test/contexts_spec.lua

was trying to update the tests to take advantage of #565, but some of the tests were not being detected correctly. This was due to the filetype not determined by `vim.filetype.match`, but set to `vim.bo.filetype` directly. Rather than adding a separate map for the directly set filetypes, I found that I could map treesitter lang to the files it maps to directly. Beyond that, we could use a similar method in this PR to get the injected treesitter languages at cursors in a file to test those as well, but that will be for a future PR, as this one is simply to fix the regression on tests.

test: map treesitter lang to test file

---

lua/treesitter-context/render.lua

This prevents a messy look if `vim.o.winborder` is changed to any type other than "none".
Context:
As of [this recently merged PR](https://github.com/neovim/neovim/pull/31074) neovim now has an option to set a default winborder. This can cause some unexpected behavior in plugins that assume the default to be "none".
This PR explicitly sets the border to `"none"` rather than `nil` so that if the user runs `:set winborder=rounded` or similar it won't cause rounded borders on the treesitter-context display.
Example without this fix:

fix: explicitly set border to 'none' when no separator

---

lua/treesitter-context/context.lua

fix: Always call parse on the treesitter parser

---

lua/treesitter-context/render.lua

When setting extmarks the win_col virt_text_pos value is invalid, however it is returned in details whenever an extmark is created with some virt_text_win_col. Handle this case by setting the value to nil.
If this was intentional to avoid some issues with using virt_text_win_col in the context, then understandable, just wasn't sure.
Tested it locally using [my plugin](https://github.com/MeanderingProgrammer/render-markdown.nvim) which uses virt_text_win_col extmarks when showing headings in markdown:
| Original Mark | Context Before | Context After |
| ------------- | --------------- | ------------- |
| ![start](https://github.com/user-attachments/assets/fce33d9b-7807-479b-8e3c-4db1c5de0eb6) | ![before](https://github.com/user-attachments/assets/826361e4-0c07-439a-9997-d7457a0ea265) | …

fix: ignore win_col virt_text_pos value when copying extmarks

---

lua/treesitter-context/context.lua

#596 
fixes issue causing separator to cover up context

fix(render): #596 - separator overlapping context

---

doc/nvim-treesitter-context.txt
lua/treesitter-context/config.lua
lua/treesitter-context/context.lua

I liked the original idea, saw that it had not been implemented, so here goes a quick attempt at it.
It accepts any "<integer>%". The emmy types have also been updated, and so has the documentation. If the string is malformed it defaults to behaving as if `0` "no-limit" is supplied.

feat(config): max_lines accept % win.height

---

.github/workflows/ci.yml
lua/treesitter-context.lua
lua/treesitter-context/config.lua
lua/treesitter-context/context.lua
lua/treesitter-context/render.lua

- Remove `getcmdwintype()` check in Render.close().
Check is already done in `close()` which was added with
multiwindow support. Should no longer be needed higher
up.
- Combine `Render.close_other_contexts()` and
`Render.close_leaked_contexts()` into
`Render.close_contexts()`.
- Remove unnecessary tables in `is_after()`.
- Inline `delete_excess_buffers()`.
- Collapse some code.
- Rename `update_single_context()` to `update_win()`.
- Fix typing of config module.

refactor: general tidy up

---

lua/treesitter-context.lua
lua/treesitter-context/context.lua
lua/treesitter-context/render.lua
test/contexts_spec.lua

- Removes the need for the internal `all_contexts` variable.
- Remove `bufnr` argument from `Context.get()` and make `winid`
optional.

refactor: make `go_to_context()` get contexts directly

---

lua/treesitter-context.lua
lua/treesitter-context/render.lua

Not a complete fix, but should solve most issues.
Fixes #509

fix: force hl update on diagnostics and LSP

---

lua/treesitter-context/render.lua

Fix a rendering crash that occurs when starting nvim with `-c "set nomodifiable"`.
This is essentially the same issue as described in https://github.com/Saghen/blink.cmp/issues/1889

fix(render): ensure buffer is modifiable before rendering

---

plugin/treesitter-context.lua

Fixes #620
Adds back the call to setup removed in https://github.com/nvim-treesitter/nvim-treesitter-context/commit/4cc55022cd159ec69ceda06e425af603603f3d01, which made calling `setup` mandatory.

fix: call setup in plugin directory

---

queries/rust/context.scm
test/lang/test.rs

Adding rusts variable to block binding as a context

feat(rust): add let = block context
