nvim-treesitter/nvim-treesitter-context

lua/treesitter-context.lua

Fixes #3 
Depends on https://github.com/neovim/neovim/pull/13117

Add Scroll autocmd

---

lua/treesitter-context.lua

Now restores window view state, such as `curswant`.
Should solve the issue in #11.
Let me know if there's any more issues! 👍

Fix wincol() approach for get_gutter_width() using getcurpos() and setpos()

---

lua/treesitter-context.lua

Based on the work on @oberblastmeister in #27

Full context

---

lua/treesitter-context.lua

Prevents glitchyness when editing at the end of the line when there is context displayed

Calculate gutter width less often 

---

lua/treesitter-context.lua

Hopefully this solves the gutter width issue once and for all.

Use ffi to get gutter width

---

README.md
lua/treesitter-context.lua

Hi, 
thanks for this awesome plugin 👍🏻 
One thing that was missing for me was an easy way to toggle the context window. Maybe you want to have it upstream :)

Add TSContextToggle command

---

README.md
lua/treesitter-context.lua
lua/treesitter-context/config.lua

Hi,
I am still a big fan of this plugin. Thanks man :)
I missed an option to disable this plugin at load. Maybe you want to have it upstream :)

Add option to enable/disable plugin at start

---

lua/treesitter-context.lua

Here's a test of before / after using synchronized tmux panes
https://user-images.githubusercontent.com/506791/122118297-ba7a2b80-cddc-11eb-8d06-d067cac2f7bd.mp4
There was already a method for throttling the update, but it wasn't called in the important places and the logic could be simplified.

Debounce context update for performance improvement

---

README.md
lua/treesitter-context.lua

Adds the zindex option with a default value of `40`.
Closes #114

Add Z-index option

---

lua/treesitter-context.lua

feat: add config.separator

---

lua/treesitter-context.lua

Fixes #121, by restoring the previous behavior.

fix: truncate outer context lines

---

README.md

Correct default patterns in README.md

---

lua/treesitter-context.lua

This PR aligns the side scroll of the context to the side scroll of the page.

feat: Add side scrolling to context

---

lua/treesitter-context.lua

Feel free to remove the `chore` commit if it is deemed gratuitous. I've ensured that it's the latest commit to easily be redacted.

Verilog defaults

---

README.md
queries/latex/context.scm

feat: add query for latex

---

queries/c/context.scm

Add preprocessor if/ifdef/ifndef blocks for c/cpp.

feat(c/cpp): add preprocessor directives

---

queries/typescriptreact/context.scm

Tree sitter handles typescript tsx files as their own file type / grammer.
I'd be happy to add some tests, but I'm not familiar with them at all and they look a bit intimidating without actual lua nor treesitter knowledge :sweat_smile:

feat: add tsx support

---

queries/rust/context.scm
test/ts_context_spec.lua

Specify the end node on some queries and add some others.

feat: additional rust queries

---

README.md
queries/verilog/context.scm
test/test.v

Add support verilog.
Show some import contexts which very convenient in my daily work.

Support verilog.

---

queries/php/context.scm

Let me know if I've done something wrong with these queries; it looks good to me though.

feat: add php switch/case statements to context

---

README.md
queries/r/context.scm
test/test.r

add R queries

---

README.md
queries/dart/context.scm
test/test.dart

I wasn't aware of how the test files are used (looked like manual test files so that is what I used).
Let me know if I am missing something!

Add dart support

---

queries/javascript/context.scm
queries/tsx/context.scm
queries/typescript/context.scm
test/test.ts
test/test.tsx

Making a couple of modifications I found useful while developing:
- Added generator functions for TS, TSX and JS files
- Took example from Rust declarations to inline parameters and return types for TS and TSX contexts
- Added a couple of examples

feat: adding generator to js/ts/tsx and improvements for ts

---

README.md
queries/c_sharp/context.scm
test/test.cs

Add queries for parser [c_sharp](https://github.com/tree-sitter/tree-sitter-c-sharp)

feat: add c# support

---

README.md
queries/ocaml/context.scm
queries/ocaml_interface/context.scm

This is unlikely to be the optimal solution but it fills my needs.
Found [this comment](https://github.com/nvim-treesitter/nvim-treesitter/issues/3672#issuecomment-1280788385) about the `inherits` behaviour.

feat: add initial OCaml support

---

lua/treesitter-context.lua

I believe this will fix #211 without requiring much (barely any) added complexity within this function. Rather than deal with the statuscolumn at all, with this PR users can use the `line_numbers` option to control how the numbers are rendered for each line of the context window i.e. they can re-arrange the padding as needed to align with a custom statusline
In the example above in order to match with my statuscolumn which outputs a string that looks like
(note this is not exactly how my statuscolumn is laid out)
```
1,200  |
1,201  |
```
I used
```lua
line_numbers = function(lnum, width)
-- split the padding to surround the number to match the layout of my statuscolumn
return ('  %-' .. (width - 4) .. 'd   '):format(lnum)
end,
```
Hopefully this solution allows this plugin to remain …

feat(line_numbers): show statuscolumn if available

---

lua/treesitter-context.lua

feat: render statuscolumn highlights for context window

---

lua/treesitter-context.lua

fix: use TreesitterContextLineNumber for statuscolumn

---

README.md
queries/zig/context.scm
test/test.zig

feat: add zig queries

---

README.md
queries/bash/context.scm
queries/fish/context.scm
test/test.bash
test/test.fish

slight duplication since fish & bash have some shared node names

Fish support & bash update

---

queries/css/context.scm
queries/scss/context.scm
test/test.css
test/test.scss

forgot to implement multiline support in the last (s)css pr (#244)

feat: (s)css multiline support

---

queries/ruby/context.scm

tested with a simple ruby file

Add singleton_method context query for Ruby

---

queries/go/context.scm
test/test.go

feat(go): multiline & switch-case

---

queries/smali/context.scm

feat: add Smali

---

queries/go/context.scm

feat(go): support expression swich&case

---

README.md
queries/html/context.scm
test/test.html

feat(html): html support

---

README.md
queries/cuda/context.scm
test/test.cu

cuda context should be same as cpp context

feat: add cuda

---

README.md
queries/norg/context.scm
test/test.norg

This adds queries for the norg filetype used by [neorg](https://github.com/nvim-neorg/neorg).

feat: add norg queries

---

README.md
lua/treesitter-context.lua

feat: add config.on_attach

---

lua/treesitter-context.lua

I was debugging some slowness in my Neovim config and it turns out it was mostly caused by nvim-treesitter-context.
nvim-treesitter-context has some kind of throttling for updates already, but the way it worked was still causing quite a lot of CPU usage on my end, mostly when scrolling.
This PR changes the implementation of the throttle function by a simple debounce.
The original implementation mentioned a fix for flickering, but I don't notice any flickering with the new impementation.

perf: added debounce for calculating context

---

lua/treesitter-context.lua

Requires https://github.com/neovim/neovim/pull/22710

perf: use max_start_depth in iter_matches

---

README.md
queries/nix/context.scm
test/test.nix

I'm unsure if this is the optimal solution to this issue, but it seems like a good starting place.

feat: add initial Nix support

---

lua/treesitter-context.lua

fix: context not updated when on_attach is false

---

queries/lua/context.scm

This add a query for repeat_statement.

feat(lua): support repeat

---

queries/python/context.scm

fix(python): update query according to treesitter

---

README.md
queries/odin/context.scm
test/test.odin

Adding support for [odin](https://odin-lang.org/)

Add support for Odin

---

lua/treesitter-context.lua

feat: highlight injection langs

---

lua/treesitter-context/render.lua

Seems to be a typo I think while doing the recent refactors

fix: add missing comma

---

README.md
queries/nim/context.scm
test/test.nim

PR in nvim-treesitter repo still pending: https://github.com/nvim-treesitter/nvim-treesitter/pull/5437

feat(nim): added nim support

---

README.md
queries/jsonnet/context.scm
test/test.jsonnet

This PR adds initial support for Jsonnet.

feat: add jsonnet support

---

README.md
queries/liquidsoap/context.scm
test/test.liq

This PR adds liquidsoap tree-sitter context queries.
Liquidsoap is scripting language for creating media streams and more. It's got about [1.5k](https://github.com/search?type=code&q=NOT+is%3Afork+path%3A*.liq) script files on github.
Thanks for your consideration!

Add liquidsoap

---

README.md
queries/fennel/context.scm
test/test.fnl

Needs tests, haven't looked well into how you guys do those yet.
Anyone who's inspired to write them: feel free to do so.

Add Fennel support.

---

README.md
queries/clojure/context.scm
test/test.clj

Needs tests, haven't looked well into how you guys do those yet.
Anyone who's inspired to write them: feel free to do so.

Add Clojure support.

---

README.md
queries/solidity/context.scm
test/test.sol

yul is still pending, will keep it for later

feat: add context for solidity

---

README.md
queries/apex/context.scm
test/test.apex

- context.scm
- test.apex
- README update

add Salesforce Apex language support

---

queries/c/context.scm
test/test.c

Add switch + case to C

---

README.md
queries/groovy/context.scm
test/test.groovy

Groovy and Jenkinsfile is very nested, so this tool is perfect for getting the context of where you are working in Jenkinsfiles

Added Groovy (and Jenkinsfile) syntax

---

queries/svelte/context.scm

closes https://github.com/nvim-treesitter/nvim-treesitter/issues/6156

fix(svelte): update queries from parser change

---

README.md
queries/ruby/context.scm
test/text.rb

add rspec context to the ruby query

---

queries/julia/context.scm

fix: julia function query

---

queries/fennel/context.scm

Updated queries to support the [updated parser](https://github.com/nvim-treesitter/nvim-treesitter/pull/6460).

fix(fennel): update queries to support new parser

---

queries/fennel/context.scm

feat(fennel): improve queries

---

queries/c_sharp/context.scm

fix(c_sharp): update queries from upstream

---

queries/haskell/context.scm

See: 
- https://github.com/nvim-treesitter/nvim-treesitter/pull/6580
- https://github.com/tree-sitter/tree-sitter-haskell/pull/120
This also adds a few queries.

fix(haskell): update quereis for tree-sitter-haskell v0.21.0 rewrite

---

queries/svelte/context.scm

I was getting some errors about the modified items. I'm relatively new to tree-sitter and parsers/queries/etc. so if there's a better way to do this, please feel free to let me know!

Update svelte queries

---

README.md
queries/proto/context.scm
test/lang/test.proto

Support proto files https://protobuf.dev/

feat(proto): add proto support

---

lua/treesitter-context/context.lua
lua/treesitter-context/render.lua

- **fix: handle contexts with zero width**
- **fix: avoid using -1 as a column**

Avoid using end_col as -1

---

lua/treesitter-context/render.lua

feat: copy over extmarks

---

lua/treesitter-context/context.lua

Check if buffer is loaded

---

CONTRIBUTING.md

since i've made the mistake once or twice.
feel free to reject if this is redundant due to CI.

docs(CONTRIBUTING): commit message instructions

---

README.md

docs: Add section about overriding language files

---

lua/treesitter-context.lua

https://github.com/nvim-treesitter/nvim-treesitter-context/pull/480

feat: multiwindow support; throttling mechanism

---

doc/nvim-treesitter-context.txt
lua/treesitter-context.lua
lua/treesitter-context/config.lua

If I understand feature request correctly, this PR should close https://github.com/nvim-treesitter/nvim-treesitter-context/issues/31 issue.

feat: multiwindow support; add multiwindow option

---

README.md
lua/treesitter-context.lua

Fixes https://github.com/nvim-treesitter/nvim-treesitter-context/issues/512

fix: multiwindow support; context window leak

---

queries/glsl/context.scm
test/lang/test.glsl

Adds the function definition to the glsl context support.

feat(glsl): add support for glsl

---

queries/c/context.scm
test/lang/test.c

feat(c): add declaration support

---

lua/treesitter-context/render.lua

Ref https://github.com/neovim/neovim/pull/32060

fix: render stacked 'statuscolumn' highlights

---

lua/treesitter-context/render.lua

#597
fixes issue causing gutter window inconsistency leading to window separator not being fully drawn

fix(render): Fixes #597 - inconsistent gutter_window

---

lua/treesitter-context.lua

fix: remove buftype restriction

---

README.md
doc/nvim-treesitter-context.txt
lua/treesitter-context.lua
lua/treesitter-context/cli.lua
plugin/treesitter-context.lua
test/contexts_spec.lua
test/helpers.lua
test/queries_spec.lua
test/ts_context_spec.lua

Replaced `TSContextEnable`, `TSContextDisable`,
`TSContextToggle` with `TSContext` with `enable`,
`disable` and `toggle` as subcommands.
Also moved init code into `plugin/`.

feat(cli)!: new user command interface

---

README.md
queries/kotlin/context.scm
test/lang/test.kt

I have added Kotlin support covering the following context:
- classes
- unctions
- for / while loops
- if / else if
- when
- try

feat(kotlin): added kotlin support
